package m2go

type CreditMemo struct {
	Adjustment                              float64           `json:"adjustment"`
	AdjustmentNegative                      float64           `json:"adjustment_negative"`
	AdjustmentPositive                      float64           `json:"adjustment_positive"`
	BaseAdjustment                          float64           `json:"base_adjustment"`
	BaseAdjustmentNegative                  float64           `json:"base_adjustment_negative"`
	BaseAdjustmentPositive                  float64           `json:"base_adjustment_positive"`
	BaseCurrencyCode                        string            `json:"base_currency_code"`
	BaseDiscountAmount                      float64           `json:"base_discount_amount"`
	BaseGrandTotal                          float64           `json:"base_grand_total"`
	BaseDiscountTaxCompensationAmount       float64           `json:"base_discount_tax_compensation_amount"`
	BaseShippingAmount                      float64           `json:"base_shipping_amount"`
	BaseShippingDiscountTaxCompensationAmnt float64           `json:"base_shipping_discount_tax_compensation_amnt"`
	BaseShippingInclTax                     float64           `json:"base_shipping_incl_tax"`
	BaseShippingTaxAmount                   float64           `json:"base_shipping_tax_amount"`
	BaseSubtotal                            float64           `json:"base_subtotal"`
	BaseSubtotalInclTax                     float64           `json:"base_subtotal_incl_tax"`
	BaseTaxAmount                           float64           `json:"base_tax_amount"`
	BaseToGlobalRate                        float64           `json:"base_to_global_rate"`
	BaseToOrderRate                         float64           `json:"base_to_order_rate"`
	BillingAddressID                        int64             `json:"billing_address_id"`
	CreatedAt                               string            `json:"created_at"`
	CreditmemoStatus                        float64           `json:"creditmemo_status"`
	DiscountAmount                          float64           `json:"discount_amount"`
	DiscountDescription                     string            `json:"discount_description"`
	EmailSent                               float64           `json:"email_sent"`
	EntityID                                int64             `json:"entity_id"`
	GlobalCurrencyCode                      string            `json:"global_currency_code"`
	GrandTotal                              float64           `json:"grand_total"`
	DiscountTaxCompensationAmount           float64           `json:"discount_tax_compensation_amount"`
	IncrementID                             string            `json:"increment_id"`
	InvoiceID                               int64             `json:"invoice_id"`
	OrderCurrencyCode                       string            `json:"order_currency_code"`
	OrderID                                 int64             `json:"order_id"`
	ShippingAddressID                       int64             `json:"shipping_address_id"`
	ShippingAmount                          float64           `json:"shipping_amount"`
	ShippingDiscountTaxCompensationAmount   float64           `json:"shipping_discount_tax_compensation_amount"`
	ShippingInclTax                         float64           `json:"shipping_incl_tax"`
	ShippingTaxAmount                       float64           `json:"shipping_tax_amount"`
	State                                   float64           `json:"state"`
	StoreCurrencyCode                       string            `json:"store_currency_code"`
	StoreID                                 int               `json:"store_id"`
	StoreToBaseRate                         float64           `json:"store_to_base_rate"`
	StoreToOrderRate                        float64           `json:"store_to_order_rate"`
	Subtotal                                float64           `json:"subtotal"`
	SubtotalInclTax                         float64           `json:"subtotal_incl_tax"`
	TaxAmount                               float64           `json:"tax_amount"`
	TransactionID                           int64             `json:"transaction_id"`
	UpdatedAt                               string            `json:"updated_at"`
	Items                                   []*CreditmemoItem `json:"items"`
	Comments                                []struct {
		Comment             string  `json:"comment"`
		CreatedAt           string  `json:"created_at"`
		EntityID            int64   `json:"entity_id"`
		IsCustomerNotified  float64 `json:"is_customer_notified"`
		IsVisibleOnFront    float64 `json:"is_visible_on_front"`
		ParentID            int64   `json:"parent_id"`
		ExtensionAttributes struct {
		} `json:"extension_attributes"`
	} `json:"comments"`
	ExtensionAttributes struct {
		BaseCustomerBalanceAmount float64 `json:"base_customer_balance_amount"`
		CustomerBalanceAmount     float64 `json:"customer_balance_amount"`
		BaseGiftCardsAmount       float64 `json:"base_gift_cards_amount"`
		GiftCardsAmount           float64 `json:"gift_cards_amount"`
		GwBasePrice               string  `json:"gw_base_price"`
		GwPrice                   string  `json:"gw_price"`
		GwItemsBasePrice          string  `json:"gw_items_base_price"`
		GwItemsPrice              string  `json:"gw_items_price"`
		GwCardBasePrice           string  `json:"gw_card_base_price"`
		GwCardPrice               string  `json:"gw_card_price"`
		GwBaseTaxAmount           string  `json:"gw_base_tax_amount"`
		GwTaxAmount               string  `json:"gw_tax_amount"`
		GwItemsBaseTaxAmount      string  `json:"gw_items_base_tax_amount"`
		GwItemsTaxAmount          string  `json:"gw_items_tax_amount"`
		GwCardBaseTaxAmount       string  `json:"gw_card_base_tax_amount"`
		GwCardTaxAmount           string  `json:"gw_card_tax_amount"`
		AvataxIsUnbalanced        string  `json:"avatax_is_unbalanced"`
		BaseAvataxTaxAmount       string  `json:"base_avatax_tax_amount"`
		AvataxResponse            string  `json:"avatax_response"`
	} `json:"extension_attributes"`
}

type CreditmemoItem struct {
	AdditionalData                    string `json:"additional_data"`
	BaseCost                          float64    `json:"base_cost"`
	BaseDiscountAmount                float64    `json:"base_discount_amount"`
	BaseDiscountTaxCompensationAmount float64    `json:"base_discount_tax_compensation_amount"`
	BasePrice                         float64    `json:"base_price"`
	BasePriceInclTax                  float64    `json:"base_price_incl_tax"`
	BaseRowTotal                      float64    `json:"base_row_total"`
	BaseRowTotalInclTax               float64    `json:"base_row_total_incl_tax"`
	BaseTaxAmount                     float64    `json:"base_tax_amount"`
	BaseWeeeTaxAppliedAmount          float64    `json:"base_weee_tax_applied_amount"`
	BaseWeeeTaxAppliedRowAmnt         float64    `json:"base_weee_tax_applied_row_amnt"`
	BaseWeeeTaxDisposition            float64    `json:"base_weee_tax_disposition"`
	BaseWeeeTaxRowDisposition         float64    `json:"base_weee_tax_row_disposition"`
	Description                       string `json:"description"`
	DiscountAmount                    float64    `json:"discount_amount"`
	EntityID                          int    `json:"entity_id"`
	DiscountTaxCompensationAmount     float64    `json:"discount_tax_compensation_amount"`
	Name                              string `json:"name"`
	OrderItemID                       int    `json:"order_item_id"`
	ParentID                          int    `json:"parent_id"`
	Price                             float64    `json:"price"`
	PriceInclTax                      float64    `json:"price_incl_tax"`
	ProductID                         int    `json:"product_id"`
	Qty                               int    `json:"qty"`
	RowTotal                          float64    `json:"row_total"`
	RowTotalInclTax                   float64    `json:"row_total_incl_tax"`
	Sku                               string `json:"sku"`
	TaxAmount                         float64    `json:"tax_amount"`
	WeeeTaxApplied                    string `json:"weee_tax_applied"`
	WeeeTaxAppliedAmount              float64    `json:"weee_tax_applied_amount"`
	WeeeTaxAppliedRowAmount           float64    `json:"weee_tax_applied_row_amount"`
	WeeeTaxDisposition                float64    `json:"weee_tax_disposition"`
	WeeeTaxRowDisposition             float64    `json:"weee_tax_row_disposition"`
	ExtensionAttributes               struct {
		VertexTaxCodes   []string `json:"vertex_tax_codes"`
		InvoiceTextCodes []string `json:"invoice_text_codes"`
		TaxCodes         []string `json:"tax_codes"`
	} `json:"extension_attributes"`
}
