package m2go

type Invoice struct {
	BaseCurrencyCode                        string  `json:"base_currency_code"`
	BaseDiscountAmount                      float64 `json:"base_discount_amount"`
	BaseGrandTotal                          float64 `json:"base_grand_total"`
	BaseDiscountTaxCompensationAmount       float64 `json:"base_discount_tax_compensation_amount"`
	BaseShippingAmount                      float64 `json:"base_shipping_amount"`
	BaseShippingDiscountTaxCompensationAmnt float64 `json:"base_shipping_discount_tax_compensation_amnt"`
	BaseShippingInclTax                     float64 `json:"base_shipping_incl_tax"`
	BaseShippingTaxAmount                   float64 `json:"base_shipping_tax_amount"`
	BaseSubtotal                            float64 `json:"base_subtotal"`
	BaseSubtotalInclTax                     float64 `json:"base_subtotal_incl_tax"`
	BaseTaxAmount                           float64 `json:"base_tax_amount"`
	BaseTotalRefunded                       float64 `json:"base_total_refunded"`
	BaseToGlobalRate                        float64 `json:"base_to_global_rate"`
	BaseToOrderRate                         float64 `json:"base_to_order_rate"`
	BillingAddressID                        int64   `json:"billing_address_id"`
	CanVoidFlag                             float64 `json:"can_void_flag"`
	CreatedAt                               string  `json:"created_at"`
	DiscountAmount                          float64 `json:"discount_amount"`
	DiscountDescription                     string  `json:"discount_description"`
	EmailSent                               float64 `json:"email_sent"`
	EntityID                                int64   `json:"entity_id"`
	GlobalCurrencyCode                      string  `json:"global_currency_code"`
	GrandTotal                              float64 `json:"grand_total"`
	DiscountTaxCompensationAmount           float64 `json:"discount_tax_compensation_amount"`
	IncrementID                             string  `json:"increment_id"`
	IsUsedForRefund                         float64 `json:"is_used_for_refund"`
	OrderCurrencyCode                       string  `json:"order_currency_code"`
	OrderID                                 int64   `json:"order_id"`
	ShippingAddressID                       int64   `json:"shipping_address_id"`
	ShippingAmount                          float64 `json:"shipping_amount"`
	ShippingDiscountTaxCompensationAmount   float64 `json:"shipping_discount_tax_compensation_amount"`
	ShippingInclTax                         float64 `json:"shipping_incl_tax"`
	ShippingTaxAmount                       float64 `json:"shipping_tax_amount"`
	State                                   float64 `json:"state"`
	StoreCurrencyCode                       string  `json:"store_currency_code"`
	StoreID                                 int     `json:"store_id"`
	StoreToBaseRate                         float64 `json:"store_to_base_rate"`
	StoreToOrderRate                        float64 `json:"store_to_order_rate"`
	Subtotal                                float64 `json:"subtotal"`
	SubtotalInclTax                         float64 `json:"subtotal_incl_tax"`
	TaxAmount                               float64 `json:"tax_amount"`
	TotalQty                                float64 `json:"total_qty"`
	TransactionID                           string  `json:"transaction_id"`
	UpdatedAt                               string  `json:"updated_at"`
	Items                                   []*Item `json:"items"`
	Comments                                []struct {
		IsCustomerNotified  float64 `json:"is_customer_notified"`
		ParentID            int64   `json:"parent_id"`
		ExtensionAttributes struct {
		} `json:"extension_attributes"`
		Comment          string  `json:"comment"`
		IsVisibleOnFront float64 `json:"is_visible_on_front"`
		CreatedAt        string  `json:"created_at"`
		EntityID         int64   `json:"entity_id"`
	} `json:"comments"`
	ExtensionAttributes struct {
		BaseCustomerBalanceAmount           float64 `json:"base_customer_balance_amount"`
		CustomerBalanceAmount               float64 `json:"customer_balance_amount"`
		BaseGiftCardsAmount                 float64 `json:"base_gift_cards_amount"`
		GiftCardsAmount                     float64 `json:"gift_cards_amount"`
		GwBasePrice                         string  `json:"gw_base_price"`
		GwPrice                             string  `json:"gw_price"`
		GwItemsBasePrice                    string  `json:"gw_items_base_price"`
		GwItemsPrice                        string  `json:"gw_items_price"`
		GwCardBasePrice                     string  `json:"gw_card_base_price"`
		GwCardPrice                         string  `json:"gw_card_price"`
		GwBaseTaxAmount                     string  `json:"gw_base_tax_amount"`
		GwTaxAmount                         string  `json:"gw_tax_amount"`
		GwItemsBaseTaxAmount                string  `json:"gw_items_base_tax_amount"`
		GwItemsTaxAmount                    string  `json:"gw_items_tax_amount"`
		GwCardBaseTaxAmount                 string  `json:"gw_card_base_tax_amount"`
		GwCardTaxAmount                     string  `json:"gw_card_tax_amount"`
		AvataxIsUnbalanced                  string  `json:"avatax_is_unbalanced"`
		BaseAvataxTaxAmount                 string  `json:"base_avatax_tax_amount"`
		AvataxResponse                      string  `json:"avatax_response"`
		VertexTaxCalculationShippingAddress struct {
			AddressType         string   `json:"address_type"`
			City                string   `json:"city"`
			Company             string   `json:"company"`
			CountryID           string   `json:"country_id"`
			CustomerAddressID   int64    `json:"customer_address_id"`
			CustomerID          int64    `json:"customer_id"`
			Email               string   `json:"email"`
			EntityID            int64    `json:"entity_id"`
			Fax                 string   `json:"fax"`
			Firstname           string   `json:"firstname"`
			Lastname            string   `json:"lastname"`
			Middlename          string   `json:"middlename"`
			ParentID            int64    `json:"parent_id"`
			Postcode            string   `json:"postcode"`
			Prefix              string   `json:"prefix"`
			Region              string   `json:"region"`
			RegionCode          string   `json:"region_code"`
			RegionID            int64    `json:"region_id"`
			Street              []string `json:"street"`
			Suffix              string   `json:"suffix"`
			Telephone           string   `json:"telephone"`
			VatID               string   `json:"vat_id"`
			VatIsValID          int64    `json:"vat_is_valid"`
			VatRequestDate      string   `json:"vat_request_date"`
			VatRequestID        string   `json:"vat_request_id"`
			VatRequestSuccess   float64  `json:"vat_request_success"`
			ExtensionAttributes struct {
			} `json:"extension_attributes"`
		} `json:"vertex_tax_calculation_shipping_address"`
		VertexTaxCalculationBillingAddress struct {
			AddressType         string   `json:"address_type"`
			City                string   `json:"city"`
			Company             string   `json:"company"`
			CountryID           string   `json:"country_id"`
			CustomerAddressID   int64    `json:"customer_address_id"`
			CustomerID          int64    `json:"customer_id"`
			Email               string   `json:"email"`
			EntityID            int64    `json:"entity_id"`
			Fax                 string   `json:"fax"`
			Firstname           string   `json:"firstname"`
			Lastname            string   `json:"lastname"`
			Middlename          string   `json:"middlename"`
			ParentID            int64    `json:"parent_id"`
			Postcode            string   `json:"postcode"`
			Prefix              string   `json:"prefix"`
			Region              string   `json:"region"`
			RegionCode          string   `json:"region_code"`
			RegionID            int64    `json:"region_id"`
			Street              []string `json:"street"`
			Suffix              string   `json:"suffix"`
			Telephone           string   `json:"telephone"`
			VatID               string   `json:"vat_id"`
			VatIsValID          int64    `json:"vat_is_valid"`
			VatRequestDate      string   `json:"vat_request_date"`
			VatRequestID        string   `json:"vat_request_id"`
			VatRequestSuccess   float64  `json:"vat_request_success"`
			ExtensionAttributes struct {
			} `json:"extension_attributes"`
		} `json:"vertex_tax_calculation_billing_address"`
		VertexTaxCalculationOrder struct {
			AdjustmentNegative                      float64 `json:"adjustment_negative"`
			AdjustmentPositive                      float64 `json:"adjustment_positive"`
			AppliedRuleIds                          string  `json:"applied_rule_ids"`
			BaseAdjustmentNegative                  float64 `json:"base_adjustment_negative"`
			BaseAdjustmentPositive                  float64 `json:"base_adjustment_positive"`
			BaseCurrencyCode                        string  `json:"base_currency_code"`
			BaseDiscountAmount                      float64 `json:"base_discount_amount"`
			BaseDiscountCanceled                    float64 `json:"base_discount_canceled"`
			BaseDiscountInvoiced                    float64 `json:"base_discount_invoiced"`
			BaseDiscountRefunded                    float64 `json:"base_discount_refunded"`
			BaseGrandTotal                          float64 `json:"base_grand_total"`
			BaseDiscountTaxCompensationAmount       float64 `json:"base_discount_tax_compensation_amount"`
			BaseDiscountTaxCompensationInvoiced     float64 `json:"base_discount_tax_compensation_invoiced"`
			BaseDiscountTaxCompensationRefunded     float64 `json:"base_discount_tax_compensation_refunded"`
			BaseShippingAmount                      float64 `json:"base_shipping_amount"`
			BaseShippingCanceled                    float64 `json:"base_shipping_canceled"`
			BaseShippingDiscountAmount              float64 `json:"base_shipping_discount_amount"`
			BaseShippingDiscountTaxCompensationAmnt float64 `json:"base_shipping_discount_tax_compensation_amnt"`
			BaseShippingInclTax                     float64 `json:"base_shipping_incl_tax"`
			BaseShippingInvoiced                    float64 `json:"base_shipping_invoiced"`
			BaseShippingRefunded                    float64 `json:"base_shipping_refunded"`
			BaseShippingTaxAmount                   float64 `json:"base_shipping_tax_amount"`
			BaseShippingTaxRefunded                 float64 `json:"base_shipping_tax_refunded"`
			BaseSubtotal                            float64 `json:"base_subtotal"`
			BaseSubtotalCanceled                    float64 `json:"base_subtotal_canceled"`
			BaseSubtotalInclTax                     float64 `json:"base_subtotal_incl_tax"`
			BaseSubtotalInvoiced                    float64 `json:"base_subtotal_invoiced"`
			BaseSubtotalRefunded                    float64 `json:"base_subtotal_refunded"`
			BaseTaxAmount                           float64 `json:"base_tax_amount"`
			BaseTaxCanceled                         float64 `json:"base_tax_canceled"`
			BaseTaxInvoiced                         float64 `json:"base_tax_invoiced"`
			BaseTaxRefunded                         float64 `json:"base_tax_refunded"`
			BaseTotalCanceled                       float64 `json:"base_total_canceled"`
			BaseTotalDue                            float64 `json:"base_total_due"`
			BaseTotalInvoiced                       float64 `json:"base_total_invoiced"`
			BaseTotalInvoicedCost                   float64 `json:"base_total_invoiced_cost"`
			BaseTotalOfflineRefunded                float64 `json:"base_total_offline_refunded"`
			BaseTotalOnlineRefunded                 float64 `json:"base_total_online_refunded"`
			BaseTotalPaID                           int64   `json:"base_total_paid"`
			BaseTotalQtyOrdered                     float64 `json:"base_total_qty_ordered"`
			BaseTotalRefunded                       float64 `json:"base_total_refunded"`
			BaseToGlobalRate                        float64 `json:"base_to_global_rate"`
			BaseToOrderRate                         float64 `json:"base_to_order_rate"`
			BillingAddressID                        int64   `json:"billing_address_id"`
			CanShipPartially                        float64 `json:"can_ship_partially"`
			CanShipPartiallyItem                    float64 `json:"can_ship_partially_item"`
			CouponCode                              string  `json:"coupon_code"`
			CreatedAt                               string  `json:"created_at"`
			CustomerDob                             string  `json:"customer_dob"`
			CustomerEmail                           string  `json:"customer_email"`
			CustomerFirstname                       string  `json:"customer_firstname"`
			CustomerGender                          float64 `json:"customer_gender"`
			CustomerGroupID                         int64   `json:"customer_group_id"`
			CustomerID                              int64   `json:"customer_id"`
			CustomerIsGuest                         float64 `json:"customer_is_guest"`
			CustomerLastname                        string  `json:"customer_lastname"`
			CustomerMiddlename                      string  `json:"customer_middlename"`
			CustomerNote                            string  `json:"customer_note"`
			CustomerNoteNotify                      float64 `json:"customer_note_notify"`
			CustomerPrefix                          string  `json:"customer_prefix"`
			CustomerSuffix                          string  `json:"customer_suffix"`
			CustomerTaxvat                          string  `json:"customer_taxvat"`
			DiscountAmount                          float64 `json:"discount_amount"`
			DiscountCanceled                        float64 `json:"discount_canceled"`
			DiscountDescription                     string  `json:"discount_description"`
			DiscountInvoiced                        float64 `json:"discount_invoiced"`
			DiscountRefunded                        float64 `json:"discount_refunded"`
			EditIncrement                           float64 `json:"edit_increment"`
			EmailSent                               float64 `json:"email_sent"`
			EntityID                                int64   `json:"entity_id"`
			ExtCustomerID                           string  `json:"ext_customer_id"`
			ExtOrderID                              string  `json:"ext_order_id"`
			ForcedShipmentWithInvoice               float64 `json:"forced_shipment_with_invoice"`
			GlobalCurrencyCode                      string  `json:"global_currency_code"`
			GrandTotal                              float64 `json:"grand_total"`
			DiscountTaxCompensationAmount           float64 `json:"discount_tax_compensation_amount"`
			DiscountTaxCompensationInvoiced         float64 `json:"discount_tax_compensation_invoiced"`
			DiscountTaxCompensationRefunded         float64 `json:"discount_tax_compensation_refunded"`
			HoldBeforeState                         string  `json:"hold_before_state"`
			HoldBeforeStatus                        string  `json:"hold_before_status"`
			IncrementID                             string  `json:"increment_id"`
			IsVirtual                               float64 `json:"is_virtual"`
			OrderCurrencyCode                       string  `json:"order_currency_code"`
			OriginalIncrementID                     string  `json:"original_increment_id"`
			PaymentAuthorizationAmount              float64 `json:"payment_authorization_amount"`
			PaymentAuthExpiration                   float64 `json:"payment_auth_expiration"`
			ProtectCode                             string  `json:"protect_code"`
			QuoteAddressID                          int64   `json:"quote_address_id"`
			QuoteID                                 int64   `json:"quote_id"`
			RelationChildID                         string  `json:"relation_child_id"`
			RelationChildRealID                     string  `json:"relation_child_real_id"`
			RelationParentID                        string  `json:"relation_parent_id"`
			RelationParentRealID                    string  `json:"relation_parent_real_id"`
			RemoteIP                                string  `json:"remote_ip"`
			ShippingAmount                          float64 `json:"shipping_amount"`
			ShippingCanceled                        float64 `json:"shipping_canceled"`
			ShippingDescription                     string  `json:"shipping_description"`
			ShippingDiscountAmount                  float64 `json:"shipping_discount_amount"`
			ShippingDiscountTaxCompensationAmount   float64 `json:"shipping_discount_tax_compensation_amount"`
			ShippingInclTax                         float64 `json:"shipping_incl_tax"`
			ShippingInvoiced                        float64 `json:"shipping_invoiced"`
			ShippingRefunded                        float64 `json:"shipping_refunded"`
			ShippingTaxAmount                       float64 `json:"shipping_tax_amount"`
			ShippingTaxRefunded                     float64 `json:"shipping_tax_refunded"`
			State                                   string  `json:"state"`
			Status                                  string  `json:"status"`
			StoreCurrencyCode                       string  `json:"store_currency_code"`
			StoreID                                 int64   `json:"store_id"`
			StoreName                               string  `json:"store_name"`
			StoreToBaseRate                         float64 `json:"store_to_base_rate"`
			StoreToOrderRate                        float64 `json:"store_to_order_rate"`
			Subtotal                                float64 `json:"subtotal"`
			SubtotalCanceled                        float64 `json:"subtotal_canceled"`
			SubtotalInclTax                         float64 `json:"subtotal_incl_tax"`
			SubtotalInvoiced                        float64 `json:"subtotal_invoiced"`
			SubtotalRefunded                        float64 `json:"subtotal_refunded"`
			TaxAmount                               float64 `json:"tax_amount"`
			TaxCanceled                             float64 `json:"tax_canceled"`
			TaxInvoiced                             float64 `json:"tax_invoiced"`
			TaxRefunded                             float64 `json:"tax_refunded"`
			TotalCanceled                           float64 `json:"total_canceled"`
			TotalDue                                float64 `json:"total_due"`
			TotalInvoiced                           float64 `json:"total_invoiced"`
			TotalItemCount                          float64 `json:"total_item_count"`
			TotalOfflineRefunded                    float64 `json:"total_offline_refunded"`
			TotalOnlineRefunded                     float64 `json:"total_online_refunded"`
			TotalPaID                               int64   `json:"total_paid"`
			TotalQtyOrdered                         float64 `json:"total_qty_ordered"`
			TotalRefunded                           float64 `json:"total_refunded"`
			UpdatedAt                               string  `json:"updated_at"`
			Weight                                  float64 `json:"weight"`
			XForwardedFor                           string  `json:"x_forwarded_for"`
			Items                                   []struct {
				AdditionalData                      string  `json:"additional_data"`
				AmountRefunded                      float64 `json:"amount_refunded"`
				AppliedRuleIds                      string  `json:"applied_rule_ids"`
				BaseAmountRefunded                  float64 `json:"base_amount_refunded"`
				BaseCost                            float64 `json:"base_cost"`
				BaseDiscountAmount                  float64 `json:"base_discount_amount"`
				BaseDiscountInvoiced                float64 `json:"base_discount_invoiced"`
				BaseDiscountRefunded                float64 `json:"base_discount_refunded"`
				BaseDiscountTaxCompensationAmount   float64 `json:"base_discount_tax_compensation_amount"`
				BaseDiscountTaxCompensationInvoiced float64 `json:"base_discount_tax_compensation_invoiced"`
				BaseDiscountTaxCompensationRefunded float64 `json:"base_discount_tax_compensation_refunded"`
				BaseOriginalPrice                   float64 `json:"base_original_price"`
				BasePrice                           float64 `json:"base_price"`
				BasePriceInclTax                    float64 `json:"base_price_incl_tax"`
				BaseRowInvoiced                     float64 `json:"base_row_invoiced"`
				BaseRowTotal                        float64 `json:"base_row_total"`
				BaseRowTotalInclTax                 float64 `json:"base_row_total_incl_tax"`
				BaseTaxAmount                       float64 `json:"base_tax_amount"`
				BaseTaxBeforeDiscount               float64 `json:"base_tax_before_discount"`
				BaseTaxInvoiced                     float64 `json:"base_tax_invoiced"`
				BaseTaxRefunded                     float64 `json:"base_tax_refunded"`
				BaseWeeeTaxAppliedAmount            float64 `json:"base_weee_tax_applied_amount"`
				BaseWeeeTaxAppliedRowAmnt           float64 `json:"base_weee_tax_applied_row_amnt"`
				BaseWeeeTaxDisposition              float64 `json:"base_weee_tax_disposition"`
				BaseWeeeTaxRowDisposition           float64 `json:"base_weee_tax_row_disposition"`
				CreatedAt                           string  `json:"created_at"`
				Description                         string  `json:"description"`
				DiscountAmount                      float64 `json:"discount_amount"`
				DiscountInvoiced                    float64 `json:"discount_invoiced"`
				DiscountPercent                     float64 `json:"discount_percent"`
				DiscountRefunded                    float64 `json:"discount_refunded"`
				EventID                             int64   `json:"event_id"`
				ExtOrderItemID                      string  `json:"ext_order_item_id"`
				FreeShipping                        float64 `json:"free_shipping"`
				GwBasePrice                         float64 `json:"gw_base_price"`
				GwBasePriceInvoiced                 float64 `json:"gw_base_price_invoiced"`
				GwBasePriceRefunded                 float64 `json:"gw_base_price_refunded"`
				GwBaseTaxAmount                     float64 `json:"gw_base_tax_amount"`
				GwBaseTaxAmountInvoiced             float64 `json:"gw_base_tax_amount_invoiced"`
				GwBaseTaxAmountRefunded             float64 `json:"gw_base_tax_amount_refunded"`
				GwID                                int64   `json:"gw_id"`
				GwPrice                             float64 `json:"gw_price"`
				GwPriceInvoiced                     float64 `json:"gw_price_invoiced"`
				GwPriceRefunded                     float64 `json:"gw_price_refunded"`
				GwTaxAmount                         float64 `json:"gw_tax_amount"`
				GwTaxAmountInvoiced                 float64 `json:"gw_tax_amount_invoiced"`
				GwTaxAmountRefunded                 float64 `json:"gw_tax_amount_refunded"`
				DiscountTaxCompensationAmount       float64 `json:"discount_tax_compensation_amount"`
				DiscountTaxCompensationCanceled     float64 `json:"discount_tax_compensation_canceled"`
				DiscountTaxCompensationInvoiced     float64 `json:"discount_tax_compensation_invoiced"`
				DiscountTaxCompensationRefunded     float64 `json:"discount_tax_compensation_refunded"`
				IsQtyDecimal                        float64 `json:"is_qty_decimal"`
				IsVirtual                           float64 `json:"is_virtual"`
				ItemID                              int64   `json:"item_id"`
				LockedDoInvoice                     float64 `json:"locked_do_invoice"`
				LockedDoShip                        float64 `json:"locked_do_ship"`
				Name                                string  `json:"name"`
				NoDiscount                          float64 `json:"no_discount"`
				OrderID                             int64   `json:"order_id"`
				OriginalPrice                       float64 `json:"original_price"`
				ParentItemID                        int64   `json:"parent_item_id"`
				Price                               float64 `json:"price"`
				PriceInclTax                        float64 `json:"price_incl_tax"`
				ProductID                           int64   `json:"product_id"`
				ProductType                         string  `json:"product_type"`
				QtyBackordered                      float64 `json:"qty_backordered"`
				QtyCanceled                         float64 `json:"qty_canceled"`
				QtyInvoiced                         float64 `json:"qty_invoiced"`
				QtyOrdered                          float64 `json:"qty_ordered"`
				QtyRefunded                         float64 `json:"qty_refunded"`
				QtyReturned                         float64 `json:"qty_returned"`
				QtyShipped                          float64 `json:"qty_shipped"`
				QuoteItemID                         int64   `json:"quote_item_id"`
				RowInvoiced                         float64 `json:"row_invoiced"`
				RowTotal                            float64 `json:"row_total"`
				RowTotalInclTax                     float64 `json:"row_total_incl_tax"`
				RowWeight                           float64 `json:"row_weight"`
				Sku                                 string  `json:"sku"`
				StoreID                             int64   `json:"store_id"`
				TaxAmount                           float64 `json:"tax_amount"`
				TaxBeforeDiscount                   float64 `json:"tax_before_discount"`
				TaxCanceled                         float64 `json:"tax_canceled"`
				TaxInvoiced                         float64 `json:"tax_invoiced"`
				TaxPercent                          float64 `json:"tax_percent"`
				TaxRefunded                         float64 `json:"tax_refunded"`
				UpdatedAt                           string  `json:"updated_at"`
				WeeeTaxApplied                      string  `json:"weee_tax_applied"`
				WeeeTaxAppliedAmount                float64 `json:"weee_tax_applied_amount"`
				WeeeTaxAppliedRowAmount             float64 `json:"weee_tax_applied_row_amount"`
				WeeeTaxDisposition                  float64 `json:"weee_tax_disposition"`
				WeeeTaxRowDisposition               float64 `json:"weee_tax_row_disposition"`
				Weight                              float64 `json:"weight"`
				ProductOption                       struct {
					ExtensionAttributes struct {
						CustomOptions []struct {
							OptionID            string `json:"option_id"`
							OptionValue         string `json:"option_value"`
							ExtensionAttributes struct {
								FileInfo struct {
									Base64EncodedData string `json:"base64_encoded_data"`
									Type              string `json:"type"`
									Name              string `json:"name"`
								} `json:"file_info"`
							} `json:"extension_attributes"`
						} `json:"custom_options"`
						BundleOptions []struct {
							OptionID            int64     `json:"option_id"`
							OptionQty           float64   `json:"option_qty"`
							OptionSelections    []float64 `json:"option_selections"`
							ExtensionAttributes struct {
							} `json:"extension_attributes"`
						} `json:"bundle_options"`
						DownloadableOption struct {
							DownloadableLinks []float64 `json:"downloadable_links"`
						} `json:"downloadable_option"`
						GiftcardItemOption struct {
							GiftcardAmount         string  `json:"giftcard_amount"`
							CustomGiftcardAmount   float64 `json:"custom_giftcard_amount"`
							GiftcardSenderName     string  `json:"giftcard_sender_name"`
							GiftcardRecipientName  string  `json:"giftcard_recipient_name"`
							GiftcardSenderEmail    string  `json:"giftcard_sender_email"`
							GiftcardRecipientEmail string  `json:"giftcard_recipient_email"`
							GiftcardMessage        string  `json:"giftcard_message"`
							ExtensionAttributes    struct {
								GiftcardCreatedCodes []string `json:"giftcard_created_codes"`
							} `json:"extension_attributes"`
						} `json:"giftcard_item_option"`
						ConfigurableItemOptions []struct {
							OptionID            string  `json:"option_id"`
							OptionValue         float64 `json:"option_value"`
							ExtensionAttributes struct {
							} `json:"extension_attributes"`
						} `json:"configurable_item_options"`
					} `json:"extension_attributes"`
				} `json:"product_option"`
				ExtensionAttributes struct {
					GiftMessage struct {
						GiftMessageID       int64  `json:"gift_message_id"`
						CustomerID          int64  `json:"customer_id"`
						Sender              string `json:"sender"`
						Recipient           string `json:"recipient"`
						Message             string `json:"message"`
						ExtensionAttributes struct {
							EntityID                   string `json:"entity_id"`
							EntityType                 string `json:"entity_type"`
							WrappingID                 int64  `json:"wrapping_id"`
							WrappingAllowGiftReceipt   bool   `json:"wrapping_allow_gift_receipt"`
							WrappingAddPrfloat64edCard bool   `json:"wrapping_add_prfloat64ed_card"`
						} `json:"extension_attributes"`
					} `json:"gift_message"`
					GwID                    string   `json:"gw_id"`
					GwBasePrice             string   `json:"gw_base_price"`
					GwPrice                 string   `json:"gw_price"`
					GwBaseTaxAmount         string   `json:"gw_base_tax_amount"`
					GwTaxAmount             string   `json:"gw_tax_amount"`
					GwBasePriceInvoiced     string   `json:"gw_base_price_invoiced"`
					GwPriceInvoiced         string   `json:"gw_price_invoiced"`
					GwBaseTaxAmountInvoiced string   `json:"gw_base_tax_amount_invoiced"`
					GwTaxAmountInvoiced     string   `json:"gw_tax_amount_invoiced"`
					GwBasePriceRefunded     string   `json:"gw_base_price_refunded"`
					GwPriceRefunded         string   `json:"gw_price_refunded"`
					GwBaseTaxAmountRefunded string   `json:"gw_base_tax_amount_refunded"`
					GwTaxAmountRefunded     string   `json:"gw_tax_amount_refunded"`
					HsCode                  string   `json:"hs_code"`
					UnitName                string   `json:"unit_name"`
					UnitAmount              float64  `json:"unit_amount"`
					PrefProgramIndicator    string   `json:"pref_program_indicator"`
					VertexTaxCodes          []string `json:"vertex_tax_codes"`
					InvoiceTextCodes        []string `json:"invoice_text_codes"`
					TaxCodes                []string `json:"tax_codes"`
				} `json:"extension_attributes"`
			} `json:"items"`
			BillingAddress struct {
				AddressType         string   `json:"address_type"`
				City                string   `json:"city"`
				Company             string   `json:"company"`
				CountryID           string   `json:"country_id"`
				CustomerAddressID   int64    `json:"customer_address_id"`
				CustomerID          int64    `json:"customer_id"`
				Email               string   `json:"email"`
				EntityID            int64    `json:"entity_id"`
				Fax                 string   `json:"fax"`
				Firstname           string   `json:"firstname"`
				Lastname            string   `json:"lastname"`
				Middlename          string   `json:"middlename"`
				ParentID            int64    `json:"parent_id"`
				Postcode            string   `json:"postcode"`
				Prefix              string   `json:"prefix"`
				Region              string   `json:"region"`
				RegionCode          string   `json:"region_code"`
				RegionID            int64    `json:"region_id"`
				Street              []string `json:"street"`
				Suffix              string   `json:"suffix"`
				Telephone           string   `json:"telephone"`
				VatID               string   `json:"vat_id"`
				VatIsValID          int64    `json:"vat_is_valid"`
				VatRequestDate      string   `json:"vat_request_date"`
				VatRequestID        string   `json:"vat_request_id"`
				VatRequestSuccess   float64  `json:"vat_request_success"`
				ExtensionAttributes struct {
				} `json:"extension_attributes"`
			} `json:"billing_address"`
			Payment         Payment `json:"payment"`
			StatusHistories []struct {
				Comment             string  `json:"comment"`
				CreatedAt           string  `json:"created_at"`
				EntityID            int64   `json:"entity_id"`
				EntityName          string  `json:"entity_name"`
				IsCustomerNotified  float64 `json:"is_customer_notified"`
				IsVisibleOnFront    float64 `json:"is_visible_on_front"`
				ParentID            int64   `json:"parent_id"`
				Status              string  `json:"status"`
				ExtensionAttributes struct {
				} `json:"extension_attributes"`
			} `json:"status_histories"`
			ExtensionAttributes struct {
				ShippingAssignments []struct {
					Shipping struct {
						Address struct {
							AddressType         string   `json:"address_type"`
							City                string   `json:"city"`
							Company             string   `json:"company"`
							CountryID           string   `json:"country_id"`
							CustomerAddressID   int64    `json:"customer_address_id"`
							CustomerID          int64    `json:"customer_id"`
							Email               string   `json:"email"`
							EntityID            int64    `json:"entity_id"`
							Fax                 string   `json:"fax"`
							Firstname           string   `json:"firstname"`
							Lastname            string   `json:"lastname"`
							Middlename          string   `json:"middlename"`
							ParentID            int64    `json:"parent_id"`
							Postcode            string   `json:"postcode"`
							Prefix              string   `json:"prefix"`
							Region              string   `json:"region"`
							RegionCode          string   `json:"region_code"`
							RegionID            int64    `json:"region_id"`
							Street              []string `json:"street"`
							Suffix              string   `json:"suffix"`
							Telephone           string   `json:"telephone"`
							VatID               string   `json:"vat_id"`
							VatIsValID          int64    `json:"vat_is_valid"`
							VatRequestDate      string   `json:"vat_request_date"`
							VatRequestID        string   `json:"vat_request_id"`
							VatRequestSuccess   float64  `json:"vat_request_success"`
							ExtensionAttributes struct {
							} `json:"extension_attributes"`
						} `json:"address"`
						Method string `json:"method"`
						Total  struct {
							BaseShippingAmount                      float64 `json:"base_shipping_amount"`
							BaseShippingCanceled                    float64 `json:"base_shipping_canceled"`
							BaseShippingDiscountAmount              float64 `json:"base_shipping_discount_amount"`
							BaseShippingDiscountTaxCompensationAmnt float64 `json:"base_shipping_discount_tax_compensation_amnt"`
							BaseShippingInclTax                     float64 `json:"base_shipping_incl_tax"`
							BaseShippingInvoiced                    float64 `json:"base_shipping_invoiced"`
							BaseShippingRefunded                    float64 `json:"base_shipping_refunded"`
							BaseShippingTaxAmount                   float64 `json:"base_shipping_tax_amount"`
							BaseShippingTaxRefunded                 float64 `json:"base_shipping_tax_refunded"`
							ShippingAmount                          float64 `json:"shipping_amount"`
							ShippingCanceled                        float64 `json:"shipping_canceled"`
							ShippingDiscountAmount                  float64 `json:"shipping_discount_amount"`
							ShippingDiscountTaxCompensationAmount   float64 `json:"shipping_discount_tax_compensation_amount"`
							ShippingInclTax                         float64 `json:"shipping_incl_tax"`
							ShippingInvoiced                        float64 `json:"shipping_invoiced"`
							ShippingRefunded                        float64 `json:"shipping_refunded"`
							ShippingTaxAmount                       float64 `json:"shipping_tax_amount"`
							ShippingTaxRefunded                     float64 `json:"shipping_tax_refunded"`
							ExtensionAttributes                     struct {
							} `json:"extension_attributes"`
						} `json:"total"`
						ExtensionAttributes struct {
						} `json:"extension_attributes"`
					} `json:"shipping"`
					Items []struct {
						AdditionalData                      string  `json:"additional_data"`
						AmountRefunded                      float64 `json:"amount_refunded"`
						AppliedRuleIds                      string  `json:"applied_rule_ids"`
						BaseAmountRefunded                  float64 `json:"base_amount_refunded"`
						BaseCost                            float64 `json:"base_cost"`
						BaseDiscountAmount                  float64 `json:"base_discount_amount"`
						BaseDiscountInvoiced                float64 `json:"base_discount_invoiced"`
						BaseDiscountRefunded                float64 `json:"base_discount_refunded"`
						BaseDiscountTaxCompensationAmount   float64 `json:"base_discount_tax_compensation_amount"`
						BaseDiscountTaxCompensationInvoiced float64 `json:"base_discount_tax_compensation_invoiced"`
						BaseDiscountTaxCompensationRefunded float64 `json:"base_discount_tax_compensation_refunded"`
						BaseOriginalPrice                   float64 `json:"base_original_price"`
						BasePrice                           float64 `json:"base_price"`
						BasePriceInclTax                    float64 `json:"base_price_incl_tax"`
						BaseRowInvoiced                     float64 `json:"base_row_invoiced"`
						BaseRowTotal                        float64 `json:"base_row_total"`
						BaseRowTotalInclTax                 float64 `json:"base_row_total_incl_tax"`
						BaseTaxAmount                       float64 `json:"base_tax_amount"`
						BaseTaxBeforeDiscount               float64 `json:"base_tax_before_discount"`
						BaseTaxInvoiced                     float64 `json:"base_tax_invoiced"`
						BaseTaxRefunded                     float64 `json:"base_tax_refunded"`
						BaseWeeeTaxAppliedAmount            float64 `json:"base_weee_tax_applied_amount"`
						BaseWeeeTaxAppliedRowAmnt           float64 `json:"base_weee_tax_applied_row_amnt"`
						BaseWeeeTaxDisposition              float64 `json:"base_weee_tax_disposition"`
						BaseWeeeTaxRowDisposition           float64 `json:"base_weee_tax_row_disposition"`
						CreatedAt                           string  `json:"created_at"`
						Description                         string  `json:"description"`
						DiscountAmount                      float64 `json:"discount_amount"`
						DiscountInvoiced                    float64 `json:"discount_invoiced"`
						DiscountPercent                     float64 `json:"discount_percent"`
						DiscountRefunded                    float64 `json:"discount_refunded"`
						EventID                             int64   `json:"event_id"`
						ExtOrderItemID                      string  `json:"ext_order_item_id"`
						FreeShipping                        float64 `json:"free_shipping"`
						GwBasePrice                         float64 `json:"gw_base_price"`
						GwBasePriceInvoiced                 float64 `json:"gw_base_price_invoiced"`
						GwBasePriceRefunded                 float64 `json:"gw_base_price_refunded"`
						GwBaseTaxAmount                     float64 `json:"gw_base_tax_amount"`
						GwBaseTaxAmountInvoiced             float64 `json:"gw_base_tax_amount_invoiced"`
						GwBaseTaxAmountRefunded             float64 `json:"gw_base_tax_amount_refunded"`
						GwID                                int64   `json:"gw_id"`
						GwPrice                             float64 `json:"gw_price"`
						GwPriceInvoiced                     float64 `json:"gw_price_invoiced"`
						GwPriceRefunded                     float64 `json:"gw_price_refunded"`
						GwTaxAmount                         float64 `json:"gw_tax_amount"`
						GwTaxAmountInvoiced                 float64 `json:"gw_tax_amount_invoiced"`
						GwTaxAmountRefunded                 float64 `json:"gw_tax_amount_refunded"`
						DiscountTaxCompensationAmount       float64 `json:"discount_tax_compensation_amount"`
						DiscountTaxCompensationCanceled     float64 `json:"discount_tax_compensation_canceled"`
						DiscountTaxCompensationInvoiced     float64 `json:"discount_tax_compensation_invoiced"`
						DiscountTaxCompensationRefunded     float64 `json:"discount_tax_compensation_refunded"`
						IsQtyDecimal                        float64 `json:"is_qty_decimal"`
						IsVirtual                           float64 `json:"is_virtual"`
						ItemID                              int64   `json:"item_id"`
						LockedDoInvoice                     float64 `json:"locked_do_invoice"`
						LockedDoShip                        float64 `json:"locked_do_ship"`
						Name                                string  `json:"name"`
						NoDiscount                          float64 `json:"no_discount"`
						OrderID                             int64   `json:"order_id"`
						OriginalPrice                       float64 `json:"original_price"`
						ParentItemID                        int64   `json:"parent_item_id"`
						Price                               float64 `json:"price"`
						PriceInclTax                        float64 `json:"price_incl_tax"`
						ProductID                           int64   `json:"product_id"`
						ProductType                         string  `json:"product_type"`
						QtyBackordered                      float64 `json:"qty_backordered"`
						QtyCanceled                         float64 `json:"qty_canceled"`
						QtyInvoiced                         float64 `json:"qty_invoiced"`
						QtyOrdered                          float64 `json:"qty_ordered"`
						QtyRefunded                         float64 `json:"qty_refunded"`
						QtyReturned                         float64 `json:"qty_returned"`
						QtyShipped                          float64 `json:"qty_shipped"`
						QuoteItemID                         int64   `json:"quote_item_id"`
						RowInvoiced                         float64 `json:"row_invoiced"`
						RowTotal                            float64 `json:"row_total"`
						RowTotalInclTax                     float64 `json:"row_total_incl_tax"`
						RowWeight                           float64 `json:"row_weight"`
						Sku                                 string  `json:"sku"`
						StoreID                             int64   `json:"store_id"`
						TaxAmount                           float64 `json:"tax_amount"`
						TaxBeforeDiscount                   float64 `json:"tax_before_discount"`
						TaxCanceled                         float64 `json:"tax_canceled"`
						TaxInvoiced                         float64 `json:"tax_invoiced"`
						TaxPercent                          float64 `json:"tax_percent"`
						TaxRefunded                         float64 `json:"tax_refunded"`
						UpdatedAt                           string  `json:"updated_at"`
						WeeeTaxApplied                      string  `json:"weee_tax_applied"`
						WeeeTaxAppliedAmount                float64 `json:"weee_tax_applied_amount"`
						WeeeTaxAppliedRowAmount             float64 `json:"weee_tax_applied_row_amount"`
						WeeeTaxDisposition                  float64 `json:"weee_tax_disposition"`
						WeeeTaxRowDisposition               float64 `json:"weee_tax_row_disposition"`
						Weight                              float64 `json:"weight"`
						ProductOption                       struct {
							ExtensionAttributes struct {
								CustomOptions []struct {
									OptionID            string `json:"option_id"`
									OptionValue         string `json:"option_value"`
									ExtensionAttributes struct {
										FileInfo struct {
											Base64EncodedData string `json:"base64_encoded_data"`
											Type              string `json:"type"`
											Name              string `json:"name"`
										} `json:"file_info"`
									} `json:"extension_attributes"`
								} `json:"custom_options"`
								BundleOptions []struct {
									OptionID            int64     `json:"option_id"`
									OptionQty           float64   `json:"option_qty"`
									OptionSelections    []float64 `json:"option_selections"`
									ExtensionAttributes struct {
									} `json:"extension_attributes"`
								} `json:"bundle_options"`
								DownloadableOption struct {
									DownloadableLinks []float64 `json:"downloadable_links"`
								} `json:"downloadable_option"`
								GiftcardItemOption struct {
									GiftcardAmount         string  `json:"giftcard_amount"`
									CustomGiftcardAmount   float64 `json:"custom_giftcard_amount"`
									GiftcardSenderName     string  `json:"giftcard_sender_name"`
									GiftcardRecipientName  string  `json:"giftcard_recipient_name"`
									GiftcardSenderEmail    string  `json:"giftcard_sender_email"`
									GiftcardRecipientEmail string  `json:"giftcard_recipient_email"`
									GiftcardMessage        string  `json:"giftcard_message"`
									ExtensionAttributes    struct {
										GiftcardCreatedCodes []string `json:"giftcard_created_codes"`
									} `json:"extension_attributes"`
								} `json:"giftcard_item_option"`
								ConfigurableItemOptions []struct {
									OptionID            string  `json:"option_id"`
									OptionValue         float64 `json:"option_value"`
									ExtensionAttributes struct {
									} `json:"extension_attributes"`
								} `json:"configurable_item_options"`
							} `json:"extension_attributes"`
						} `json:"product_option"`
						ExtensionAttributes struct {
							GiftMessage struct {
								GiftMessageID       int64  `json:"gift_message_id"`
								CustomerID          int64  `json:"customer_id"`
								Sender              string `json:"sender"`
								Recipient           string `json:"recipient"`
								Message             string `json:"message"`
								ExtensionAttributes struct {
									EntityID                   string `json:"entity_id"`
									EntityType                 string `json:"entity_type"`
									WrappingID                 int64  `json:"wrapping_id"`
									WrappingAllowGiftReceipt   bool   `json:"wrapping_allow_gift_receipt"`
									WrappingAddPrfloat64edCard bool   `json:"wrapping_add_prfloat64ed_card"`
								} `json:"extension_attributes"`
							} `json:"gift_message"`
							GwID                    string   `json:"gw_id"`
							GwBasePrice             string   `json:"gw_base_price"`
							GwPrice                 string   `json:"gw_price"`
							GwBaseTaxAmount         string   `json:"gw_base_tax_amount"`
							GwTaxAmount             string   `json:"gw_tax_amount"`
							GwBasePriceInvoiced     string   `json:"gw_base_price_invoiced"`
							GwPriceInvoiced         string   `json:"gw_price_invoiced"`
							GwBaseTaxAmountInvoiced string   `json:"gw_base_tax_amount_invoiced"`
							GwTaxAmountInvoiced     string   `json:"gw_tax_amount_invoiced"`
							GwBasePriceRefunded     string   `json:"gw_base_price_refunded"`
							GwPriceRefunded         string   `json:"gw_price_refunded"`
							GwBaseTaxAmountRefunded string   `json:"gw_base_tax_amount_refunded"`
							GwTaxAmountRefunded     string   `json:"gw_tax_amount_refunded"`
							HsCode                  string   `json:"hs_code"`
							UnitName                string   `json:"unit_name"`
							UnitAmount              float64  `json:"unit_amount"`
							PrefProgramIndicator    string   `json:"pref_program_indicator"`
							VertexTaxCodes          []string `json:"vertex_tax_codes"`
							InvoiceTextCodes        []string `json:"invoice_text_codes"`
							TaxCodes                []string `json:"tax_codes"`
						} `json:"extension_attributes"`
					} `json:"items"`
					StockID             int64 `json:"stock_id"`
					ExtensionAttributes struct {
					} `json:"extension_attributes"`
				} `json:"shipping_assignments"`
				PaymentAdditionalInfo []struct {
					Key   string `json:"key"`
					Value string `json:"value"`
				} `json:"payment_additional_info"`
				BaseCustomerBalanceAmount        float64 `json:"base_customer_balance_amount"`
				CustomerBalanceAmount            float64 `json:"customer_balance_amount"`
				BaseCustomerBalanceInvoiced      float64 `json:"base_customer_balance_invoiced"`
				CustomerBalanceInvoiced          float64 `json:"customer_balance_invoiced"`
				BaseCustomerBalanceRefunded      float64 `json:"base_customer_balance_refunded"`
				CustomerBalanceRefunded          float64 `json:"customer_balance_refunded"`
				BaseCustomerBalanceTotalRefunded float64 `json:"base_customer_balance_total_refunded"`
				CustomerBalanceTotalRefunded     float64 `json:"customer_balance_total_refunded"`
				AppliedTaxes                     []struct {
					Code                string  `json:"code"`
					Title               string  `json:"title"`
					Percent             float64 `json:"percent"`
					Amount              float64 `json:"amount"`
					BaseAmount          float64 `json:"base_amount"`
					ExtensionAttributes struct {
						Rates []struct {
							Code                string  `json:"code"`
							Title               string  `json:"title"`
							Percent             float64 `json:"percent"`
							ExtensionAttributes struct {
								RatePercent float64 `json:"rate_percent"`
								TaxName     string  `json:"tax_name"`
								JurisCode   string  `json:"juris_code"`
								Taxable     float64 `json:"taxable"`
								Tax         float64 `json:"tax"`
							} `json:"extension_attributes"`
						} `json:"rates"`
					} `json:"extension_attributes"`
				} `json:"applied_taxes"`
				ItemAppliedTaxes []struct {
					Type             string `json:"type"`
					ItemID           int64  `json:"item_id"`
					AssociatedItemID int64  `json:"associated_item_id"`
					AppliedTaxes     []struct {
						Code                string  `json:"code"`
						Title               string  `json:"title"`
						Percent             float64 `json:"percent"`
						Amount              float64 `json:"amount"`
						BaseAmount          float64 `json:"base_amount"`
						ExtensionAttributes struct {
							Rates []struct {
								Code                string  `json:"code"`
								Title               string  `json:"title"`
								Percent             float64 `json:"percent"`
								ExtensionAttributes struct {
									RatePercent float64 `json:"rate_percent"`
									TaxName     string  `json:"tax_name"`
									JurisCode   string  `json:"juris_code"`
									Taxable     float64 `json:"taxable"`
									Tax         float64 `json:"tax"`
								} `json:"extension_attributes"`
							} `json:"rates"`
						} `json:"extension_attributes"`
					} `json:"applied_taxes"`
					ExtensionAttributes struct {
					} `json:"extension_attributes"`
				} `json:"item_applied_taxes"`
				ConvertingFromQuote bool `json:"converting_from_quote"`
				GiftCards           []struct {
					ID         int64   `json:"id"`
					Code       string  `json:"code"`
					Amount     float64 `json:"amount"`
					BaseAmount float64 `json:"base_amount"`
				} `json:"gift_cards"`
				BaseGiftCardsAmount   float64 `json:"base_gift_cards_amount"`
				GiftCardsAmount       float64 `json:"gift_cards_amount"`
				BaseGiftCardsInvoiced float64 `json:"base_gift_cards_invoiced"`
				GiftCardsInvoiced     float64 `json:"gift_cards_invoiced"`
				BaseGiftCardsRefunded float64 `json:"base_gift_cards_refunded"`
				GiftCardsRefunded     float64 `json:"gift_cards_refunded"`
				GiftMessage           struct {
					GiftMessageID       int64  `json:"gift_message_id"`
					CustomerID          int64  `json:"customer_id"`
					Sender              string `json:"sender"`
					Recipient           string `json:"recipient"`
					Message             string `json:"message"`
					ExtensionAttributes struct {
						EntityID                   string `json:"entity_id"`
						EntityType                 string `json:"entity_type"`
						WrappingID                 int64  `json:"wrapping_id"`
						WrappingAllowGiftReceipt   bool   `json:"wrapping_allow_gift_receipt"`
						WrappingAddPrfloat64edCard bool   `json:"wrapping_add_prfloat64ed_card"`
					} `json:"extension_attributes"`
				} `json:"gift_message"`
				GwID                     string  `json:"gw_id"`
				GwAllowGiftReceipt       string  `json:"gw_allow_gift_receipt"`
				GwAddCard                string  `json:"gw_add_card"`
				GwBasePrice              string  `json:"gw_base_price"`
				GwPrice                  string  `json:"gw_price"`
				GwItemsBasePrice         string  `json:"gw_items_base_price"`
				GwItemsPrice             string  `json:"gw_items_price"`
				GwCardBasePrice          string  `json:"gw_card_base_price"`
				GwCardPrice              string  `json:"gw_card_price"`
				GwBaseTaxAmount          string  `json:"gw_base_tax_amount"`
				GwTaxAmount              string  `json:"gw_tax_amount"`
				GwItemsBaseTaxAmount     string  `json:"gw_items_base_tax_amount"`
				GwItemsTaxAmount         string  `json:"gw_items_tax_amount"`
				GwCardBaseTaxAmount      string  `json:"gw_card_base_tax_amount"`
				GwCardTaxAmount          string  `json:"gw_card_tax_amount"`
				GwBasePriceInclTax       string  `json:"gw_base_price_incl_tax"`
				GwPriceInclTax           string  `json:"gw_price_incl_tax"`
				GwItemsBasePriceInclTax  string  `json:"gw_items_base_price_incl_tax"`
				GwItemsPriceInclTax      string  `json:"gw_items_price_incl_tax"`
				GwCardBasePriceInclTax   string  `json:"gw_card_base_price_incl_tax"`
				GwCardPriceInclTax       string  `json:"gw_card_price_incl_tax"`
				GwBasePriceInvoiced      string  `json:"gw_base_price_invoiced"`
				GwPriceInvoiced          string  `json:"gw_price_invoiced"`
				GwItemsBasePriceInvoiced string  `json:"gw_items_base_price_invoiced"`
				GwItemsPriceInvoiced     string  `json:"gw_items_price_invoiced"`
				GwCardBasePriceInvoiced  string  `json:"gw_card_base_price_invoiced"`
				GwCardPriceInvoiced      string  `json:"gw_card_price_invoiced"`
				GwBaseTaxAmountInvoiced  string  `json:"gw_base_tax_amount_invoiced"`
				GwTaxAmountInvoiced      string  `json:"gw_tax_amount_invoiced"`
				GwItemsBaseTaxInvoiced   string  `json:"gw_items_base_tax_invoiced"`
				GwItemsTaxInvoiced       string  `json:"gw_items_tax_invoiced"`
				GwCardBaseTaxInvoiced    string  `json:"gw_card_base_tax_invoiced"`
				GwCardTaxInvoiced        string  `json:"gw_card_tax_invoiced"`
				GwBasePriceRefunded      string  `json:"gw_base_price_refunded"`
				GwPriceRefunded          string  `json:"gw_price_refunded"`
				GwItemsBasePriceRefunded string  `json:"gw_items_base_price_refunded"`
				GwItemsPriceRefunded     string  `json:"gw_items_price_refunded"`
				GwCardBasePriceRefunded  string  `json:"gw_card_base_price_refunded"`
				GwCardPriceRefunded      string  `json:"gw_card_price_refunded"`
				GwBaseTaxAmountRefunded  string  `json:"gw_base_tax_amount_refunded"`
				GwTaxAmountRefunded      string  `json:"gw_tax_amount_refunded"`
				GwItemsBaseTaxRefunded   string  `json:"gw_items_base_tax_refunded"`
				GwItemsTaxRefunded       string  `json:"gw_items_tax_refunded"`
				GwCardBaseTaxRefunded    string  `json:"gw_card_base_tax_refunded"`
				GwCardTaxRefunded        string  `json:"gw_card_tax_refunded"`
				RewardPofloat64sBalance  float64 `json:"reward_pofloat64s_balance"`
				RewardCurrencyAmount     float64 `json:"reward_currency_amount"`
				BaseRewardCurrencyAmount float64 `json:"base_reward_currency_amount"`
				AvataxResponse           string  `json:"avatax_response"`
			} `json:"extension_attributes"`
		} `json:"vertex_tax_calculation_order"`
	} `json:"extension_attributes"`
}
